### ISSUE TITLE
Setup Issue

### ISSUE THREAD

**Issue by gregorskii** [ACloudGuru/serverless-plugin-cloudwatch-sumologic#13]
Hi there,

I am not able to set this up.

My `package.json`:

```
{
  "dependencies": {
    "alexa-sdk": "^1.0.9"
  },
  "devDependencies": {
    "serverless-plugin-cloudwatch-sumologic": "^0.0.10"
  }
}
```

My `serverless.yml`:

```
service: alexa-lab

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  profile: /*my profile*/

custom:
  shipLogs:
    collectorUrl: /*collector-url*/

    # Optional, default pattern is "[timestamp=*Z, request_id=\"*-*\", event]"
    filterPattern: "[timestamp=*Z, request_id=\"*-*\", correlation_id=\"*-*\", event]"
    role: /*arn for role*/

functions:
  helloworld:
    handler: handlers/helloworld/handler.helloworld
    memory: 512
    timeout: 60
    events:
      - alexaSkill

  intents:
    handler: handlers/intents/handler.intents
    memory: 512
    timeout: 60
    events:
      - alexaSkill

```

The role was extended from `CloudWatchEventsInvocationAccess`.

Running `sls deploy` nothing happens related to Logging.

```
 ▲ projects/Sandbox/alexa-lab sls version                                                                                                                                                                       
1.13.2
```

Using node locally:

v7.9.0

Thanks
